version: '3.8'

services:
  web:
    build: ./client #tell docker-compose where to find the Dockerfile
    ports:
      - '3000:3000'
  api:
    build: ./server
    ports:
      - '4000:4000'
    environment:
      DB_URL: mongodb://db/docktest
  db:
    image: mongo:6.0.10-jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - react-node-chat:/data/db

volumes:
  react-node-chat:
